import React from 'react';
import './MemberCenterpage.css';

const AgentFeedbackScreen = () => {
  return (
    <div className='memberContent'>
      <div class='agent_feedback_list hide'>
        <div class='sr_tab'>
          <ul class='sr_tab_title'>
            <li class='on'>
              <h2>电子游艺</h2>
            </li>
            <li>
              <h2>真人游戏</h2>
            </li>
            <li>
              <h2>体育游戏</h2>
            </li>
            <li>
              <h2>捕鱼游戏</h2>
            </li>
            <li>
              <h2>彩票游戏</h2>
            </li>
          </ul>
          <div class='tableStyle1'>
            <table>
              <thead>
                <tr>
                  <th>代理级别</th>
                  <th>团队业绩/日</th>
                  <th>反佣额度</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>VIP1</td>
                  <td>1+</td>
                  <td>每万元反佣20元</td>
                </tr>
                <tr>
                  <td>VIP2</td>
                  <td>2000+</td>
                  <td>每万元反佣25元</td>
                </tr>
                <tr>
                  <td>VIP3</td>
                  <td>10000+</td>
                  <td>每万元反佣30元</td>
                </tr>
                <tr>
                  <td>VIP4</td>
                  <td>30000+</td>
                  <td>每万元反佣35元</td>
                </tr>
                <tr>
                  <td>VIP5</td>
                  <td>50000+</td>
                  <td>每万元反佣40元</td>
                </tr>
                <tr>
                  <td>VIP6</td>
                  <td>70000+</td>
                  <td>每万元反佣45元</td>
                </tr>
                <tr>
                  <td>VIP7</td>
                  <td>100000+</td>
                  <td>每万元反佣50元</td>
                </tr>
                <tr>
                  <td>VIP8</td>
                  <td>150000+</td>
                  <td>每万元反佣55元</td>
                </tr>
                <tr>
                  <td>VIP9</td>
                  <td>200000+</td>
                  <td>每万元反佣60元</td>
                </tr>
                <tr>
                  <td>VIP10</td>
                  <td>300000+</td>
                  <td>每万元反佣65元</td>
                </tr>
                <tr>
                  <td>VIP11</td>
                  <td>500000+</td>
                  <td>每万元反佣70元</td>
                </tr>
                <tr>
                  <td>VIP12</td>
                  <td>800000+</td>
                  <td>每万元反佣75元</td>
                </tr>
                <tr>
                  <td>VIP13</td>
                  <td>1200000+</td>
                  <td>每万元反佣80元</td>
                </tr>
                <tr>
                  <td>VIP14</td>
                  <td>1600000+</td>
                  <td>每万元反佣85元</td>
                </tr>
                <tr>
                  <td>VIP15</td>
                  <td>2000000+</td>
                  <td>每万元反佣90元</td>
                </tr>
                <tr>
                  <td>VIP16</td>
                  <td>3000000+</td>
                  <td>每万元反佣95元</td>
                </tr>
                <tr>
                  <td>VIP17</td>
                  <td>4000000+</td>
                  <td>每万元反佣100元</td>
                </tr>
                <tr>
                  <td>VIP18</td>
                  <td>5000000+</td>
                  <td>每万元反佣105元</td>
                </tr>
                <tr>
                  <td>VIP19</td>
                  <td>6000000+</td>
                  <td>每万元反佣110元</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AgentFeedbackScreen;
